#! /bin/bash
source /opt/ros/kinetic/setup.bash && source /path/to/cartographer/install_isolated/setup.bash
roslaunch $PWD/launch/visualize_pbstream.launch \
           config_path:=$PWD/config/ \
           pbstream_filename:=/path/to/pbstream