#! /bin/bash
source /opt/ros/kinetic/setup.bash && source /path/to/cartographer/install_isolated/setup.bash
file_list=""
for file in "path/to/rosbag/files/"*; do
    [[ -f "$file" ]] && file_list+="${file} "
done
echo "$file_list"
roslaunch $PWD/launch/offline_warthog_3d_ouster.launch \
 bag_filename:="$file_list"  \
 config_path:=$PWD/config/
